project:
  type: book

book:
  title: "Death, Destruction, and Data"
  subtitle: "An Intro to Using Data to Study International Conflict"
  author: "Miles D. Williams"
  date: "1/18/2026"
  chapters:
    - index.qmd
    - 01_what_is_war.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

